const redirectUrlArr = [
  { 'madhur-sachdev-inspiro-marketing': 'madhur-sachdev-sales-marketing' },
  { 'kamal-kalra-human-insurance-professional': 'kamal-kalra-insurance-professional' },
  { 'tinkoo-oha-eye-technician': 'tinku-ojha-eye-technician' },
  { 'amit-bhargav-marketing': 'ankit-bhargav-marketing' },
  { 'saiyan-singhvi-construction': 'sainyam-singhvi-construction' },
  { 'kratin-gupta-construction': 'kritin-gupta-construction' },
  { 'ap-gupta-education-academia': 'ap-gupta-hospital-health-care' },
  { 'mukul-dixit-education-academia': 'mukul-dixit-hospital-health-care' },
  { 'priti-agarwal-education-academia': 'priti-agarwal-hospital-health-care' },
  { 'rahul-agarwal-education-academia': 'rahul-agarwal-hospital-health-care' },
  { 'mukesh-wadhwani-ashoka-bakery-catering': 'mukesh-madhwani-ashoka-bakery-catering' },
  { 'mahendra-singh-chauhan-photographer': 'mahendra-singh-chauhan-wall-arts' },
  { 'kamal-kalra-human-resource-professional': 'kamal-kalra-human-insurance-professional' },
  { 'shanti-lal-joshi-counseling': 'sunil-joshi-counseling' },
  { 'ekta-tiwari-fashion-apparel': 'ekta-takiar-fashion-apparel' },
  { 'dinkar-narayan-ss-education-academia': 'dinkar-narayan-education-academia' },
  { 'manihar-gurani-retail': 'manohar-gurani-retail' },
  { 'siddharth-chakraborty-restaurants': 'siddhartha-chakraborty-restaurants' },
  { 'amit-jothwani-education': 'amit-jotwani-education' },
  { 'jyoti-sandot-education-academia': 'jyoti-sarangdvot-education-academia' },
  { 'avesh-holi-restaurants': 'avesh-oli-restaurants' },
  { 'dr-ravi-kumar-hospital-health-care': 'dr-kumar-hospital-health-care' },
  { 'neha-sakka-telecommunications': 'neha-sakka-oil-energy' },
  { 'saurabh-singhvi-education-academia': 'saurabh-singhvi-manufacturing' },
  { 'priti-agarwal-hospital-health-care': 'preeti-agrawal-hospital-health-care' },
  { 'madhubala-chauhan-education-academia': 'madhubala-chauhan-hospital-health-care' },
  { 'brajmohan-meena-education-academia': 'brajmohan-meena-other' },
  { 'chotu-suman-education-academia': 'chotu-suman-other' },
  { 'dugal-shah-education-academia': 'druval-shah-education-academia' },
  { 'priyanka-rathore-travel-hospitality': 'priyanka-rajput-travel-hospitality' },
  { 'mukesh-chawda-government-politics': 'mukesh-chavda-government-politics' },
  { 'kiran-dangi-arts-entertainment': 'kirti-dangi-arts-entertainment' },
  { 'om-bunkar-legal-services': 'om-bunkar-government' },
  { 'tanjua-wellness-healer': 'tanuja-wellness-healer' },
  { 'sanjay-joshi-outsourcing-offshoring': 'sanay-joshi-outsourcing-offshoring' },
  { 'manjula-modi-social-work': 'manjula-bordia-social-work' },
  { 'himanshu-nayak-marine-shipping': 'himanshu-banjara-marine-shipping' },
  { 'dr-nikhil-bhakal-hospital-health-care': 'dr-nitin-bhakal-hospital-health-care' },
  { 'taani-mehta-arts-entertainment': 'taani-mehta-arts-entertainment-Influencer' },
  { 'taani-mehta-arts-entertainment-delhi': 'taani-mehta-arts-entertainment-Influencer' },
  { 'taani-mehta-arts-entertainment-new-delhi': 'taani-mehta-arts-entertainment-Influencer' },
  { 'sejal-jodhawat-education-academia': 'sejal-samar-jodhawat-education-academia' },
  { 'dr-ajit-jain-education-academia': 'dr-ajit-jain-music-dance-academies' },
  { 'harsh-patidar-education-academia': 'harsh-patidar-music-dance-academies' },
  { 'madhuri-wadhwa-education-academia': 'madhuri-wadhwa-music-dance-academies' },
  { 'neeraj-jain-arts-entertainment': 'neeraj-jain-music-dance-academies' },
  { 'udit-vershnay-education-academia': 'udit-vershney-education-academia' },
  { 'sanyogeeta-singh-education-academia': 'sanyogita-singh-education-academia' },
  { 'jigar-sharma-outsourcing-offshoring': 'jigar-sharma-ecommerce' },
  { 'angad-chabra-building-materials': 'angad-chhabra-building-materials' },
  { 'anil-chajed-manufacturing': 'anil-chhajed-manufacturing' },
  { 'dr-ankush-srivastav-education-academia': 'dr-ankush-srivastava-education-academia' },
  { 'dr-chaudhary-health-wellness-fitness': 'dr-choudhary-health-wellness-fitness' },
  { 'bhavar-seth-social-work': 'bhanwar-seth-social-work' },
  { 'bhavar-singh-social-work': 'bhanwar-singh-social-work' },
  { 'zulfikar-bandukwalla-building-materials': 'zulfikar-bandookwala-building-materials' },
  { 'yogesh-acharaya-education-academia': 'yogesh-acharya-education-academia' },
  { 'usha-vishwkarma-social-work': 'usha-vishwakarma-social-work' },
  { 'surbhi-singh-social-work': 'shubhi-singh-social-work' },
  { 'supnal-sharma-education-academia': 'swapnil-sharma-education-academia' },
  { 'suman-bhichar-education-academia': 'suman-bhichhar-education-academia' },
  { 'sheetal-shekawat-retail': 'sheetal-shekhawat-retail' },
  { 'saurabh-dana-travel-hospitality': 'sourabh-dana-travel-hospitality' },
  { 'rajkumar-pattawat-education-academia': 'rajkumar-fattawat-education-academia' },
  { 'jyoti-sarangdvot-education-academia': 'jyoti-sarangdevot-education-academia' },
  { 'jogender-singh-education-academia': 'yogendra-saini-education-academia' },
  { 'himank-dheniwal-technology': 'himank-dhenwal-technology' },
  { 'goverdhan-jhala-travel-hospitality': 'govardhan-jhala-travel-hospitality' },
  { 'chavi-rao-sports': 'chhavi-rao-sports' },
  { 'rashika-kulshreshtha-food-beverage': 'raashika-kulshreshtha-food-beverage' },
  { 'prakashchand-barmal-retail': 'prakashchand-barber-retail' },
  { 'vijay-sarupriya-technology': 'vijay-sarupria-technology' },
  { 'pankaj-katara-education-academia': 'pankaj-khatana-education-academia' },
  { 'udaybhan-singh-travel-hospitality': 'udaibhan-singh-travel-hospitality' },
  { 'hirak-majumdar-textiles': 'hirak-majumdar-arts-entertainment' },
  { 'harish-bhuvan-startups': 'harish-bhuvan-hospital-health-care' },
  { 'nishtha-pandey-startups': 'nishtha-pandey-architecture-design' },
  { 'amit-talesra-manufacturing': 'amit-talesara-manufacturing' },
  { 'asha-talesra-social-work': 'asha-talesara-social-work' },
  { 'gunit-bhargava-health-wellness-fitness': 'guneet-bhargava-health-wellness-fitness' },
  { 'manmeet-matharu-': 'manmeet-matharu-makeup-studios-salons-spas' },
  { 'sanil-jadhav-fashion-apparel': 'sanil-jadhav-fashion-apparel-mumbai' },
  { 'anshumala-gupta-education-academia': 'anshumala-gupta-education-academia-new-delhi' },
  { 'ruchika-bhanawat-architecture-design': 'ruchira-bhanawat-architecture-design' },
  { 'romi-kothari-education-academia': 'rovi-kothari-education-academia' },
  {
    'kavita-balasubramanyam-health-wellness-fitness':
      'kavitha-balasubramanian-health-wellness-fitness',
  },
  { 'prabhavi-wadhwani-fashion-apparel': 'prathvi-wadhwani-fashion-apparel' },
  { 'dr-aman-sen-education-academia': 'dr-hemant-sen-education-academia' },
  { 'neeraj-jain-arts-entertainment': 'neeraj-sain-arts-entertainment' },
  { 'sushant-bardi-startups': 'sushant-barde-startups' },
  { 'aditi-baghrecha-marketing': 'aditi-bagrecha-marketing' },
  { 'tanvi-goyal-makeup-studios-salons-spas': 'tanvi-kg-makeup-studios-salons-spas' },
  { 'mukta-ghoshal-health-wellness-fitness': 'smily-mukta-ghoshal-health-wellness-fitness' },
  { 'yogendra-saini-education-academia': 'dr-jogendra-singh-education-academia' },
  { 'priyanka-lotankae-music-dance-academies': 'priyanka-lotankar-music-dance-academies'},
  { 'monika-heda-architecture-design': 'monika-heda-marketing'},
  { 'srisha-duvvuri-real-estate': 'sirisha-duvvuri-real-estate'},
  { 'iqbal-sadka-luxury-goods-jewelry': 'iqbal-sakka-luxury-goods-jewelry'},
  { 'janak-choubisa-education-academia': 'chandra-prakash-choubisa-education-academia'}
];

export default redirectUrlArr;
